### PR TITLE
I nominate...... CHIP!

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
@chipsenkbeil @rorygraves

**Comment by chipsenkbeil** [comment]
Got to love that title. Anyway, @fommil was mentioning a standalone debugger as a potential addition to the tooling family. I'd agree that a standalone debugger in the vein of the one available for Ensime would be a powerful asset to the Scala tooling ecosystem. We've got a standalone command line debugger already, and there were other plans drawn up for a browser-based integration, graphical desktop debugger via JavaFX, abstractions and standards for non-JVM debugging (Scala Native/ScalaJS), etc.

**Comment by fommil** [comment]
related:

- moving the debugger out of ensime-server https://github.com/ensime/ensime-server/issues/1907
- standing up a standalone server https://github.com/ensime/scala-debugger/issues/364 (that may communicate with ensime server or any other LSP to get information it needs)

**Comment by rorygraves** [comment]
Seconded

**Comment by propensive** [comment]
Hi @chipsenkbeil! If you're currently employed, could you let me know your employer? They will need to be included in the "affiliations" section, even if you're not representing them. This is just so electors have transparency. Thanks!

**Comment by chipsenkbeil** [comment]
@propensive, my current employer is Facebook, although I must make it clear that I am in no way representing them. I've been given permission to work on my debugger project on my own time.

**Pull request merged**
