### PR TITLE
Nominate Guillaume Martres for the STP-WG

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by SethTisue** [comment]
seconded

**Comment by propensive** [comment]
Guillaume has already verbally accepted this, though he's currently on vacation.

**Comment by propensive** [comment]
I note that the title of the PR says to nominate Guillaume for the STP-WG, though the nomination mentions only the LSP-WG. Which did you intend, @nicolasstucki?

**Comment by propensive** [comment]
I took executive action and made his nomination for both, at least partly because we need more candidates to the STP-WG... This can always be changed in a follow-up PR.

**Pull request merged**
