### PR TITLE
Nominate Borja Lorente

### PR DESCRIPTION
**Pull request by heathermiller**
@blorente is a research engineer at Northeastern University and at the Czech Technical University. He's done a bunch of work in the past several months building tools to analyze the usage (patterns) of implicits across dozens (to even thousands) of Scala code bases. He'll be writing up a blog article shortly explaining some of those results (it's very cool! Some observations you may expect, others you may not!)

### CODE REVIEW

**Comment by olafurpg** [comment]
Seconded! @blorente has done great work using SemanticDB to analyze Scala code in the wild

**Comment by propensive** [comment]
Do you accept the nomination, @blorente?

**Comment by propensive** [comment]
@olafurpg Are you able to contact @blorente to get verbal (or better) confirmation that he's happy to stand, please?

**Comment by olafurpg** [comment]
I've pinged @blorente. He contacted me last night before this PR so it's good to merge I think.

**Comment by propensive** [comment]
Ok, that's good enough for me - thanks!

**Comment by blorente** [comment]
Sorry, timezone confusion.

I agree to this nomination.

**Comment by propensive** [comment]
Thanks, @blorente!

**Pull request merged**
