### PR TITLE
Nominate Andy Scott

### PR DESCRIPTION
**Pull request by johnynek**
I think it is essential that we have someone working full time on bazel on the working group. Andy would be a great addition!

### CODE REVIEW

**Comment by propensive** [comment]
Just to confirm, do you accept the nomination, @andyscott?

**Comment by andyscott** [comment]
@propensive Yes definitely. Happy to participate!

**Comment by olafurpg** [comment]
Seconded!

**Comment by propensive** [comment]
Too slow, @olafurpg. You already seconded it before it was merged! ;)

**Comment by andyscott** [comment]
You're just too fast, @propensive 😄.

**Pull request merged**
